"""empty message

Revision ID: 891c5ef975ac
Revises: db554221b75d
Create Date: 2022-05-31 05:44:46.331274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891c5ef975ac'
down_revision = 'db554221b75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', null=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
